//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserCredential
    {
        public int AutoIncID { get; set; }
        [DataType(DataType.EmailAddress), Required, Display(Name = "Email Address")]
        public string emailAddress { get; set; }
        [DataType(DataType.Password), Required, Display(Name = "Password"), StringLength(20, MinimumLength = 8)]
        public string password { get; set; }
        [Required, Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Required, Display(Name = "Last Name")]
        public string LastName { get; set; }
    }
}
